#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

# Load the dependencies
include $(LIB_GMSLE_PATH)/enums.mk

## Define the default configuration

GMSLE_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)
GMSLE_WARNINGS ?= $(GMSLE_WARNINGS_YES)
GMSLE_ERRORS   ?= $(GMSLE_ERRORS_YES)

GMSLE_ECHO ?= echo

GMSLE_FALSE_PREFER   ?= $(GMSLE_PREFER_MAKE)
# GMSLE_FALSE_PREFER ?= $(GMSLE_PREFER_GUILE)
# GMSLE_FALSE_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_FALSE_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_TRUE_PREFER   ?= $(GMSLE_PREFER_MAKE)
# GMSLE_TRUE_PREFER ?= $(GMSLE_PREFER_GUILE)
# GMSLE_TRUE_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_TRUE_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)
