#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

# Load the dependencies
include $(LIB_GMSLE_PATH)/enums.mk

## Define the default configuration

GMSLE_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)
GMSLE_WARNINGS ?= $(GMSLE_WARNINGS_YES)
GMSLE_ERRORS   ?= $(GMSLE_ERRORS_YES)

GMSLE_AWK     ?= awk
GMSLE_COMMAND ?= command -v
GMSLE_ECHO    ?= echo
GMSLE_GREP    ?= grep
GMSLE_SED     ?= sed
GMSLE_TEST    ?= test

GMSLE_AND_PREFER   ?= $(GMSLE_PREFER_MAKE)
# GMSLE_AND_PREFER ?= $(GMSLE_PREFER_GUILE)
# GMSLE_AND_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_AND_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_COMMAND_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_COMMAND_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_COMMAND_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_FALSE_PREFER   ?= $(GMSLE_PREFER_MAKE)
# GMSLE_FALSE_PREFER ?= $(GMSLE_PREFER_GUILE)
# GMSLE_FALSE_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_FALSE_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_IF_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_IF_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_IF_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_NAND_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_NAND_PREFER ?= $(GMSLE_PREFER_MAKE)
# GMSLE_NAND_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_NAND_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_NOR_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_NOR_PREFER ?= $(GMSLE_PREFER_MAKE)
# GMSLE_NOR_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_NOR_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_NOT_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_NOT_PREFER ?= $(GMSLE_PREFER_MAKE)
# GMSLE_NOT_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_NOT_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_OR_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_OR_PREFER ?= $(GMSLE_PREFER_MAKE)
# GMSLE_OR_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_OR_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_SEMVER_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_SEMVER_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_SEMVER_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_STRIP_PREFER   ?= $(GMSLE_PREFER_GUILE)
# GMSLE_STRIP_PREFER ?= $(GMSLE_PREFER_AWK)
# GMSLE_STRIP_PREFER ?= $(GMSLE_PREFER_SED)
# GMSLE_STRIP_PREFER ?= $(GMSLE_PREFER_GREP)
GMSLE_STRIP_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_TRUE_PREFER   ?= $(GMSLE_PREFER_MAKE)
# GMSLE_TRUE_PREFER ?= $(GMSLE_PREFER_GUILE)
# GMSLE_TRUE_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_TRUE_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)

GMSLE_XOR_PREFER   ?= $(GMSLE_PREFER_MAKE)
# GMSLE_XOR_PREFER ?= $(GMSLE_PREFER_GUILE)
# GMSLE_XOR_PREFER ?= $(GMSLE_PREFER_SHELL)
GMSLE_XOR_INCLUDE  ?= $(GMSLE_INCLUDE_AUTOMATIC)
