#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

# Include all the tests
include $(LIB_GMSLE_PATH)/test/lib/gmsle_and/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_command/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_false/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_if/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_nand/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_nor/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_not/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_or/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_semver/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_strip/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_true/GNUmakefile
include $(LIB_GMSLE_PATH)/test/lib/gmsle_xor/GNUmakefile
