#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target
    include $(LIB_GMSLE_PATH)/lib/gmsle_target/gmsle_target_make.mk
    gmsle_target = $(call gmsle_target_make,$(1),$(2),$(3))
endif #gmsle_target
