#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target_odt2pdf
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_odt2pdf/gmsle_target_odt2pdf_name.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_odt2pdf/gmsle_target_odt2pdf_deps.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_odt2pdf/gmsle_target_odt2pdf_dependee.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_odt2pdf/gmsle_target_odt2pdf_dependency.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_odt2pdf/gmsle_target_odt2pdf.mk
endif #gmsle_target_odt2pdf
