#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

# Include all the internal tests
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_abspath.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_addprefix.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_addsuffix.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_and.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_basename.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_dir.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_eval.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_findstring.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_firstword.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_guile.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_if.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_join.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_lastword.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_notdir.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_or.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_realpath.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_sort.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_strip.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_subst.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_suffix.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_word.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_wordlist.mk
include $(LIB_GMSLE_PATH)/test/lib/internal/__gmsle_has_words.mk
