#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target_touch
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_touch/gmsle_target_touch_name.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_touch/gmsle_target_touch_deps.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_touch/gmsle_target_touch_dependee.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_touch/gmsle_target_touch_dependency.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_touch/gmsle_target_touch.mk
endif #gmsle_target_touch
