#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target_ln
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_ln/gmsle_target_ln_name.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_ln/gmsle_target_ln_deps.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_ln/gmsle_target_ln_dependee.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_ln/gmsle_target_ln_dependency.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_ln/gmsle_target_ln.mk
endif #gmsle_target_ln
