#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target_clean
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_clean/gmsle_target_clean_name.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_clean/gmsle_target_clean_deps.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_clean/gmsle_target_clean_dependee.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_clean/gmsle_target_clean_dependency.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_clean/gmsle_target_clean.mk
endif #gmsle_target_clean
