#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

# Include all the components

ifeq '$(GMSLE_ABSPATH_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_abspath/GNUmakefile
endif

ifeq '$(GMSLE_ADDPREFIX_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_addprefix/GNUmakefile
endif

ifeq '$(GMSLE_ADDSUFFIX_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_addsuffix/GNUmakefile
endif

ifeq '$(GMSLE_AND_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_and/GNUmakefile
endif

ifeq '$(GMSLE_BASENAME_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_basename/GNUmakefile
endif

ifeq '$(GMSLE_COMMAND_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_command/GNUmakefile
endif

ifeq '$(GMSLE_DIR_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_dir/GNUmakefile
endif

ifeq '$(GMSLE_EVAL_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_eval/GNUmakefile
endif

ifeq '$(GMSLE_FALSE_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_false/GNUmakefile
endif

ifeq '$(GMSLE_FINDSTRING_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_findstring/GNUmakefile
endif

ifeq '$(GMSLE_FIRSTWORD_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_firstword/GNUmakefile
endif

ifeq '$(GMSLE_IF_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_if/GNUmakefile
endif

ifeq '$(GMSLE_JOIN_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_join/GNUmakefile
endif

ifeq '$(GMSLE_LASTWORD_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_lastword/GNUmakefile
endif

ifeq '$(GMSLE_NAND_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_nand/GNUmakefile
endif

ifeq '$(GMSLE_NEWLINE_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_newline/GNUmakefile
endif

ifeq '$(GMSLE_NOR_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_nor/GNUmakefile
endif

ifeq '$(GMSLE_NOT_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_not/GNUmakefile
endif

ifeq '$(GMSLE_NOTDIR_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_notdir/GNUmakefile
endif

ifeq '$(GMSLE_OR_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_or/GNUmakefile
endif

ifeq '$(GMSLE_REALPATH_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_realpath/GNUmakefile
endif

ifeq '$(GMSLE_SEMVER_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_semver/GNUmakefile
endif

ifeq '$(GMSLE_SORT_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_sort/GNUmakefile
endif

ifeq '$(GMSLE_STRIP_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_strip/GNUmakefile
endif

ifeq '$(GMSLE_SUBST_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_subst/GNUmakefile
endif

ifeq '$(GMSLE_SUFFIX_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_suffix/GNUmakefile
endif

ifeq '$(GMSLE_TARGET_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_target/GNUmakefile
endif

ifeq '$(GMSLE_TRUE_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_true/GNUmakefile
endif

ifeq '$(GMSLE_UNDEFINE_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_undefine/GNUmakefile
endif

ifeq '$(GMSLE_WORD_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_word/GNUmakefile
endif

ifeq '$(GMSLE_WORDLIST_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_wordlist/GNUmakefile
endif

ifeq '$(GMSLE_WORDS_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_words/GNUmakefile
endif

ifeq '$(GMSLE_XOR_INCLUDE)' '$(GMSLE_INCLUDE_AUTOMATIC)'
    include $(LIB_GMSLE_PATH)/lib/gmsle_xor/GNUmakefile
endif
