#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target_go_build
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_go_build/gmsle_target_go_build_name.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_go_build/gmsle_target_go_build_deps.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_go_build/gmsle_target_go_build_dependee.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_go_build/gmsle_target_go_build_dependency.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_go_build/gmsle_target_go_build.mk
endif #gmsle_target_go_build
