#!/usr/bin/env make -f
# SPDX-License-Identifier: GPL-3.0-or-later

## Smart loader

ifndef gmsle_target_adoc2html
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_adoc2html/gmsle_target_adoc2html_name.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_adoc2html/gmsle_target_adoc2html_deps.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_adoc2html/gmsle_target_adoc2html_dependee.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_adoc2html/gmsle_target_adoc2html_dependency.mk
    include $(LIB_GMSLE_PATH)/lib/gmsle_target_adoc2html/gmsle_target_adoc2html.mk
endif #gmsle_target_adoc2html
